name: Build executables

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests tqdm

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm \
                      --onefile \
                      --name fastly-scanner \
                      6.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastly-scanner-${{ matrix.os }}
          path: dist/fastly-scanner${{ matrix.os == 'windows-latest' && '.exe' || '' }}
